spring:
  datasource:
    url: jdbc:h2:file:./database
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
my:
  security:
    access-expiration-minutes: 2
    secret: VBNjVu1GYsMK95DcD/8R2RQ0kNqtjkMdAgFdy04EM9fBUnCUkhkL/AhqtThzU6lPdCv0gZ0zE611usayVgVrQTwd0IpxQIGIoT+tlh+tTnoLNctKkPr830cn6u0ygK9HzpJcjg==
